### ISSUE TITLE
Inline view strategy example in README isn't valid

### ISSUE THREAD

**Issue by peitschie** [aurelia/web-components#14]
This particular example doesn't function correctly:
```
        // with inline view strategy, via getViewStrategy
        registry.register(class MyPanel {
          // ...
          getViewStrategy() {
            return new InlineViewStrategy(
              `<template>
                <h1>\${heading}</h1>
                <slot></slot>
              </template>`
            )
          }
        }),
```

The aurelia-template class only looks for `getViewStrategy` if the instance in an `object`, rather than a `function` as this particular type is seen as.

An example test for `ce.integration.spec.ts` showing this issue:
```
  it('should initialise web component with overridden view strategy', async () => {
    class CustomElementFive {
      getViewStrategy() {
        return new InlineViewStrategy(
          `<template>One</template>`
        )
      }
    }
    const { host, registry, dispose } = await bootstrapAurelia({
      root: class RootViewModel {
        static $view = '<template></template>';
      },
      resources: [CustomElementFive]
    });
    registry.register(CustomElementFive);
    await waitForTimeout(50);

    const customComponent = document.createElement("custom-element-five");
    host.appendChild(customComponent);
    expect(customComponent.textContent).toBe('One');
    dispose();
  });
```

Here's the output if a test is created (e.g., in `ce.integration.spec.ts`):
```
 Error: Cannot determine default view strategy for object.
        at ViewLocator.getViewStrategy (webpack:///node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:807 <- test/ce.integration.spec.js:14328:15)
        at HtmlBehaviorResource.load (webpack:///node_modules/aurelia-templating/dist/native-modules/aurelia-templating.js:4226 <- test/ce.integration.spec.js:17747:49)
        at webpack:///node_modules/aurelia-framework/dist/native-modules/aurelia-framework.js:276 <- test/ce.integration.spec.js:7284:14
        at <Jasmine>
        at loadBehaviors (webpack:///node_modules/aurelia-framework/dist/native-modules/aurelia-framework.js:275 <- test/ce.integration.spec.js:7283:45)
        at webpack:///node_modules/aurelia-framework/dist/native-modules/aurelia-framework.js:395 <- test/ce.integration.spec.js:7403:24
        at next (webpack:///node_modules/aurelia-framework/dist/native-modules/aurelia-framework.js:162 <- test/ce.integration.spec.js:7170:30)
```

I had a poke, but don't yet know the aurelia internals enough to know what the right solution is.

**Comment by bigopon** [comment]
Yes, this is true, it's only valid for component that are composed via compose API of composition engine. Sorry for this @peitschie . It would be nice if you could help remove the incorrect readme in your PR.

**Comment by peitschie** [comment]
@bigopon no worries at all! These hiccups are nothing compared to the usefulness this plugin is providing 😸 ... figured I'd call them out as I went, to help make things a bit better.

I shall remove it and tack the commit on my pr!

**Comment by bigopon** [comment]
@peitschie seems like you are having good time with this plugin. Would be nice if you could throw together a small blog post or write something here https://discourse.aurelia.io/t/what-you-are-experiencing-with-aurelia/2572 when you got some spare time 😀
